// Event names for main ↔ UI communication
export const EVENT = {
  CHECK_SELECTION: 'CHECK_SELECTION',
  GET_TOKEN: 'GET_TOKEN',
  SAVE_TOKEN: 'SAVE_TOKEN',
  LOAD_TOKEN: 'LOAD_TOKEN',
  GENERATE_SPEC: 'GENERATE_SPEC',
  EXTRACTED_DATA: 'EXTRACTED_DATA',
  GEMINI_RESULT: 'GEMINI_RESULT',
  SPEC_COMPLETE: 'SPEC_COMPLETE',
  SPEC_ERROR: 'SPEC_ERROR',
} as const
